# Required substitutions
# _REGION: region of cloud run service
# _IMAGE: image name
# _SERVICE_NAME: run service name
# _IMAGE_TAG: image tag

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE}:${_IMAGE_TAG}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE}:${_IMAGE_TAG}']

  # Deploy container image to Cloud Run without traffics
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--platform'
      - 'managed'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--no-traffic'
      - '--tag'
      - 'latest'

  # Update traffics to latest tagged revision
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - ' --to-tags'
      - 'latest=100'

images:
  - gcr.io/$PROJECT_ID/${_IMAGE}:${_IMAGE_TAG}
